### ISSUE TITLE
Possible error

### ISSUE THREAD

**Issue by brianoh** [arashmanteghi/modalian#1]
I copied the section of code containing the line below from the App.js and when running in my program received an error  related to the line below. Perhaps it is because my method requires an argument, I'm not sure.
This:
    `onClose={this.toggleModal}`
Should possibly be changed to this:
    `onClose={() => { this.toggleModal() }}`

The following is my actual code which is slightly different:
    `onClose={() => { this.showConfirmMsg(false) }}`

**Comment by arashmanteghi** [comment]
If you need a confirm box in your modal, you must change `visible` props of Confirm component to true in `onClose` props of Modalian component. `onClose` means what should to do when user click on close icon.

**Comment by brianoh** [comment]
confirm is working. i have no problems. i had to change the line described however. brian
